PRAGMA foreign_keys = on;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS students;
CREATE TABLE students (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name VARCHAR (32)
);

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name VARCHAR (32),
parent_id INTEGER,
FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name VARCHAR (32),
category_id INTEGER NOT NULL,
FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS courses_students;
CREATE TABLE courses_students (
student_id INTEGER NOT NULL,
course_id INTEGER NOT NULL,
FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

COMMIT TRANSACTION;

